stages:
  - build
  - deploy

build:
  stage: build
  image: fedora:28
  before_script:
    - dnf install gcc git mingw32-gcc mingw64-gcc unzip xz zip -y
    - export CHOOSENIM_NO_ANALYTICS=1
    - export CHOOSENIM_CHOOSE_VERSION="stable"
    - curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
    - sh init.sh -y
  script:
    - export PATH="$HOME/.nimble/bin:$PATH"
    - mkdir -p dist/

    - curl -O https://nim-lang.org/download/dlls.zip
    - unzip dlls.zip

    - nimble build -d:release --passc:"-flto" -d:crosswin
    - strip main pcre64.dll
    - mkdir -p main-windows-x86_64/
    - mv main pcre64.dll main-windows-x86_64/
    - cp README.md LICENSE.md main-windows-x86_64/
    - zip -r9 dist/main-windows-x86_64.zip main-windows-x86_64/

    - rm /usr/bin/x86_64-w64-mingw32-gcc
    - ln -s /usr/bin/i686-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc
    - nimble build -d:release --passc:"-flto" -d:crosswin --cpu:i386
    - strip main pcre32.dll
    - mkdir -p main-windows-x86/
    - mv main pcre32.dll main-windows-x86/
    - cp README.md LICENSE.md main-windows-x86/
    - zip -r9 dist/main-windows-x86.zip main-windows-x86/

  artifacts:
    expire_in: 30 days
    paths:
      - dist/

deploy:
  stage: deploy
  image: fedora:28
  dependencies:
    - build
  before_script:
    - travis_retry curl -L https://github.com/tfausak/github-release/releases/download/1.2.2/github-release-$TRAVIS_OS_NAME.gz | gunzip > github-release
    - chmod a+x github-release
    # - ./github-release release --token=$GITHUB_TOKEN --owner=kdheepak --repo=travis-nim --title=$TRAVIS_TAG --tag=$TRAVIS_TAG
    - ./github-release upload --token=$GITHUB_TOKEN --owner=kdheepak --repo=travis-nim --file=dist/main-windows-x86.zip --tag=releases --name=main-windows-x86.zip
    - ./github-release upload --token=$GITHUB_TOKEN --owner=kdheepak --repo=travis-nim --file=dist/main-windows-x86_64.zip --tag=releases --name=main-windows-x86_64.zip
