dist: trusty
sudo: false

language: c

matrix:
  fast_finish: true
  include:
    - os: linux
      env:
          BUILD=linux
          CHANNEL=stable
          CROSS=""

    - os: linux
      env:
          BUILD=windows
          CHANNEL=stable
          CROSS="-d:crosswin"

    - os: osx
      compiler: clang
      env:
          BUILD=osx
          CHANNEL=stable
          CROSS=""

before_install:
  # Install nim
  - export CHOOSENIM_NO_ANALYTICS=1
  - curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
  - sh init.sh -y
  - export PATH=/Users/travis/.nimble/bin:$PATH
  - export PATH=~/.nimble/bin:$PATH
  - echo "export PATH=~/.nimble/bin:$PATH" >> ~/.profile
  - choosenim $CHANNEL
  - if [ $TRAVIS_OS_NAME == linux -a $BUILD == windows ]; then sudo apt-get install mingw-w64 gcc-mingw-w64-x86-64 binutils-mingw-w64-i686 mingw-w64-i686 gcc-mingw-w64-x86-64 binutils-mingw-w64-i686; fi
  - if [ $TRAVIS_OS_NAME == linux -a $BUILD == windows ]; then export CC=x86_64-w64-mingw32-gcc; fi

script:
  - nim c --run ./main.nim
  - nim compile -d:Release --passc:"-flto" $CROSS main.nim
  - cp ./main ./main-$BUILD

after_success:
  - travis_retry curl -L https://github.com/tfausak/github-release/releases/download/1.2.2/github-release-$TRAVIS_OS_NAME.gz | gunzip > github-release
  - chmod a+x github-release
  # - ./github-release release --token=$GITHUB_TOKEN --owner=kdheepak --repo=travis-nim --title=$TRAVIS_TAG --tag=$TRAVIS_TAG
  - ./github-release upload --token=$GITHUB_TOKEN --owner=kdheepak --repo=travis-nim --file=main-$BUILD --tag=releases --name=main-$BUILD

notifications:
  email: false

branches:
  only:
    - master

