dist: trusty
sudo: false

language: c

cache:
  directories:
    - $HOME/cache

matrix:
  fast_finish: true
  include:
    - os: linux
      env:
          BUILD=linux
          CHANNEL=stable

    - os: osx
      compiler: clang
      env:
          BUILD=osx
          CHANNEL=stable

before_install:
  # Install nim
  - export CHOOSENIM_NO_ANALYTICS=1
  - curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
  - sh init.sh -y
  - export PATH=/Users/travis/.nimble/bin:$PATH
  - export PATH=~/.nimble/bin:$PATH
  - echo "export PATH=~/.nimble/bin:$PATH" >> ~/.profile
  - choosenim $CHANNEL

script:
  - nim c --run ./main.nim
  - cp ./main ./main-$BUILD

after_success:
  - travis_retry curl -L https://github.com/tfausak/github-release/releases/download/1.2.2/github-release-$TRAVIS_OS_NAME.gz | gunzip > github-release
  - chmod a+x github-release
  # - ./github-release release --token=$GITHUB_TOKEN --owner=kdheepak --repo=travis-nim --title=$TRAVIS_TAG --tag=$TRAVIS_TAG
  - ./github-release upload --token=$GITHUB_TOKEN --owner=kdheepak --repo=travis-nim --file=main-$BUILD.tar.gz --tag=v0.1.0 --name=main-$BUILD-v0.1.0-$TRAVIS_OS_NAME-x86_64.tar.gz
  fi
notifications:
  email: false

branches:
  only:
    - master

